web/router.ex
defmodule AgileCoachCampex.Router do
  use AgileCoachCampex.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AgileCoachCampex do
    pipe_through :browser # Use the default browser stack
    resources "/", PageController, only: [:index, :create]
    resources "/organizers", OrganizerController
    resources "/programs", ProgrammeController
    resources "/gallery", GalleryController
    resources "/sponsor", SponsorController
  end

  scope "/admin", AgileCoachCampex.Admin, as: :admin do
    pipe_through :browser
    resources "/signup_opened_notifications", SignupOpenedNotificationController
    get "/login", AccessController, :login
    get "/", AccessController, :login
    get "/logout", AccessController, :logout
    post "/login", AccessController, :login_process
  end

  # Other scopes may use custom stacks.
  # scope "/api", AgileCoachCampex do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule AgileCoachCampex.LayoutView do
  use AgileCoachCampex.Web, :view

  def menu_class(conn, type) do
    state(conn.private.phoenix_controller, type)
  end

  def state(controller, type) do
    {:ok, regex} = type |> Regex.compile
    ctrl_str = controller |> Atom.to_string |> String.downcase
    if Regex.match?(regex, ctrl_str), do: "active", else: ""
  end

end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Agile Coach Camp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Agile Coach Camp in Denmark">
    <meta name="Keywords" content="agile, scrum, lean, empowerment, leadership, coaching, happiness, open space">
    <meta name="author" content="Thomas Ringling">
    <link href="http://fonts.googleapis.com/css?family=Exo+2:400,700" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="acc_container" role="main">

      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="/">
              Agile Coach Camp
            </a>
          </div>
          <ul class="nav navbar-nav">
        <li class="<%= menu_class(@conn, "page") %>"><a href="<%= page_path(@conn, :index) %>">Home<span class="sr-only">(current)</span></a></li>
        <li class="<%= menu_class(@conn, "organizer") %>"><a href="<%= organizer_path(@conn, :index) %>">Organizers<span class="sr-only">(current)</span></a></li>
        <li class="<%= menu_class(@conn, "program") %>"><a href="<%= programme_path(@conn, :index) %>">Program<span class="sr-only">(current)</span></a></li>
        <!--<li class="<%= menu_class(@conn, "gallery") %>"><a href="<%= gallery_path(@conn, :index) %>">Gallery<span class="sr-only">(current)</span></a></li>-->
        <li class="<%= menu_class(@conn, "sponsor") %>"><a href="<%= sponsor_path(@conn, :index) %>">Sponsors<span class="sr-only">(current)</span></a></li>
        <li class="<%= menu_class(@conn, "attendee") %>"style="visibility: hidden"><a href="#">Attendees<span class="sr-only">(current)</span></a></li>
        <%= if Plug.Conn.get_session(@conn, :username)!=nil do %>
          <li class="<%= menu_class(@conn, "admin") %>"><a href="<%= admin_signup_opened_notification_path(@conn, :index) %>"> Admin<span class="sr-only">(current)</span></a></li>
          <li>
            <a href="<%= admin_access_path(@conn, :logout) %>"> Logout<span class="sr-only">(current)</span></a>

          </li>


        <% end %>
        </div>
      </nav>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <%= render @view_module, @view_template, assigns %>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script>require("web/static/js/app")</script>
  </body>
</html>

web/templates/layout/application.html.eex
<!DOCTYPE html>
<html lang="en"> 
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Agile Coach Camp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Agile Coach Camp in Denmark">
    <meta name="Keywords" content="agile, scrum, lean, empowerment, leadership, coaching, happiness, open space">
    <meta name="author" content="Thomas Ringling">
    <link href="http://fonts.googleapis.com/css?family=Exo+2:400,700" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="acc_container" role="main">

      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="/">
              Agile Coach Camp
            </a>
          </div>
          <ul class="nav navbar-nav">
        <li class="<%= menu_class(@conn, "page") %>"><a href="<%= page_path(@conn, :index) %>">Home<span class="sr-only">(current)</span></a></li>
        <li class="<%= menu_class(@conn, "organizer") %>"><a href="<%= organizer_path(@conn, :index) %>">Organizers<span class="sr-only">(current)</span></a></li>
        <li class="<%= menu_class(@conn, "program") %>"><a href="<%= programme_path(@conn, :index) %>">Program<span class="sr-only">(current)</span></a></li>
        <li class="<%= menu_class(@conn, "attendee") %>"style="visibility: hidden"><a href="#">Attendees<span class="sr-only">(current)</span></a></li>
        <%= if Plug.Conn.get_session(@conn, :username)!=nil do %>
          <li class="<%= menu_class(@conn, "admin") %>"><a href="<%= admin_signup_opened_notification_path(@conn, :index) %>"> Admin<span class="sr-only">(current)</span></a></li>
          <li>
            <a href="<%= admin_access_path(@conn, :logout) %>"> Logout<span class="sr-only">(current)</span></a>
 
          </li>


        <% end %>
        </div>
      </nav>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <%= @inner %>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script>require("web/static/js/app")</script>
  </body>
</html>